CREATE TABLE IF NOT EXISTS Product(
Id INT PRIMARY KEY AUTO_INCREMENT,
Units int,
Energyclass VARCHAR(20),
Model VARCHAR(40),
AcquisitionPrice INT,
Description TEXT,
Price INT,
Manufactor VARCHAR(100),
Category INT NOT NULL,
Series INT
);

CREATE TABLE IF NOT EXISTS Customer(
Id INT PRIMARY KEY AUTO_INCREMENT,
PersonId VARCHAR(20),
EmailAdress VARCHAR(50),
HomeAdress VARCHAR(200),
TelephoneNumber VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS Purchase(
Id INT PRIMARY KEY AUTO_INCREMENT,
Customer INT,
Product INT,
FOREIGN KEY(Customer) REFERENCES Customer(Id),
FOREIGN KEY(Product) REFERENCES Product(Id)
);

CREATE TABLE IF NOT EXISTS Category(
Id INT PRIMARY KEY AUTO_INCREMENT,
CategoryName VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Serie(
Id INT PRIMARY KEY AUTO_INCREMENT,
SerieName VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS Promotion(
Id INT PRIMARY KEY AUTO_INCREMENT,
Description text,
Value INT,
Category INT
);

CREATE TABLE IF NOT EXISTS UserProfile(
UserId INT PRIMARY KEY AUTO_INCREMENT,
UserName VARCHAR(60)
);


ALTER TABLE Product
ADD FOREIGN KEY(Category) REFERENCES Category(Id),
ADD FOREIGN KEY(Series) REFERENCES Serie(Id);

ALTER TABLE Promotion
ADD FOREIGN KEY(Category) REFERENCES Category(Id);

ALTER TABLE Purchase
ADD FOREIGN KEY(Customer) REFERENCES Customer(Id),
ADD FOREIGN KEY(Product) REFERENCES Product(Id);
