CREATE TABLE IF NOT EXISTS Category(
Id INT PRIMARY KEY AUTO_INCREMENT,
CategoryName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Serie(
Id INT PRIMARY KEY AUTO_INCREMENT,
SerieName VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS Product(
Id INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(40) NOT NULL,
Units int NOT NULL,
Energyclass VARCHAR(20) NOT NULL,
Model VARCHAR(40) NOT NULL,
AcquisitionPrice INT NOT NULL,
Description TEXT NOT NULL,
Price INT NOT NULL,
Manufactor VARCHAR(100) NOT NULL,
Category INT NOT NULL,
Series INT,
FOREIGN KEY(Category) REFERENCES Category(Id),
FOREIGN KEY(Series) REFERENCES Serie(Id)
);

CREATE TABLE IF NOT EXISTS Customer(
Id INT PRIMARY KEY AUTO_INCREMENT,
PersonId VARCHAR(10) UNIQUE NOT NULL,
EmailAdress VARCHAR(50) NOT NULL,
HomeAdress VARCHAR(200) NOT NULL,
TelephoneNumber VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Purchase(
Id INT PRIMARY KEY AUTO_INCREMENT,
Customer INT NOT NULL,
Product INT NOT NULL,
Quantity INT NOT NULL,
FOREIGN KEY(Customer) REFERENCES Customer(Id),
FOREIGN KEY(Product) REFERENCES Product(Id)
);

CREATE TABLE IF NOT EXISTS Basket(
Id INT PRIMARY KEY AUTO_INCREMENT,
Customer INT NOT NULL,
Product INT NOT NULL,
Quantity INT NOT NULL,
FOREIGN KEY(Customer) REFERENCES Customer(Id),
FOREIGN KEY(Product) REFERENCES Product(Id)
);



CREATE TABLE IF NOT EXISTS Promotion(
Id INT PRIMARY KEY AUTO_INCREMENT,
Description text NOT NULL,
Value INT NOT NULL,
Category INT NOT NULL,
FOREIGN KEY(Category) REFERENCES Category(Id)
);

CREATE TABLE IF NOT EXISTS UserProfile(
UserId INT PRIMARY KEY AUTO_INCREMENT,
UserName VARCHAR(60)
);